package me.trup10ka.puby.util

import dev.kord.core.behavior.interaction.response.DeferredPublicMessageInteractionResponseBehavior

typealias DeferredResponseBehavior = DeferredPublicMessageInteractionResponseBehavior
